- hosts: localhost
  become: yes
  pre_tasks:
    - name: Update & upgrade pacman
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - update
        - upgrade
  tasks:
    - import_tasks: tasks/trizen.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/pde.yml
    - import_tasks: tasks/cmd-utils.yml
    - import_tasks: tasks/apps.yml
    - import_tasks: tasks/sudo.yml
    - import_tasks: tasks/power.yml
    - import_tasks: tasks/touchpad.yml
    - import_tasks: tasks/mpd.yml
