- name: Install Command-line utilities
  pacman: name={{item}}
  with_items:
    - lm_sensors
    - sysstat
    - htop
    - unrar
    - unzip
    - tree
    - rsync
    - imagemagick
    - nethogs
    - net-tools
    - aria2
    - bind-tools
    - python-pip
    - reflector
  tags:
    - cmd-utils
    - packages

- name: Install youtube-dl utilities
  ansible.builtin.pip: name={{item}}
  with_items:
    - youtube-dl
  tags:
    - cmd-utils
    - packages

- name: Install jcal
  become: yes
  become_user: m47h4r
  ansible.builtin.command: trizen -S --noconfirm jcal-git
  tags:
    - jcal
    - cmd-utils
    - packages
